apiVersion: v1
kind: Service
metadata:
  name: todoweb
  labels:
    app: todoweb
spec:
  selector:
    app: todoweb
  ports:
   - name: http
     port: 80
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoweb
  labels: 
    name: todoweb
spec:
  replicas: 2
  selector: 
    matchLabels: 
      app: todoweb
  template:
    metadata:
      labels:
        app: todoweb
    spec: # nginxとwebは密結合で構わないのでPodに同居させる
      volumes:
      - name: assets
        emptyDir: {} # Pod単位に割り当てられる仮想Volumeを作成
      containers:
      - name: nginx
        image: gihyodocker/nginx-nuxt:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: WORKER_PROCESSES
          value: "2"
        - name: WORKER_CONNECTIONS
          value: "1024"
        - name: LOG_STDOUT
          value: "true"
        - name: BACKEND_HOST
          value: "localhost:3000" # Podに同居しているのでlocalhostで解決可能
        volumeMounts: # 仮想Volumeをコンテナにマウント
        - mountPath: /var/www/_nuxt
          name: assets

      - name: web
        image: gihyodocker/todoweb:latest
        imagePullPolicy: Always
        lifecycle: # webコンテナ開始時に仮想Volumeにassetsファイルをコピーする
          postStart:
            exec:
              command:
              - cp
              - -R
              - /todoweb/.nuxt/dist
              - /
        ports: 
        - containerPort: 3000
        env: 
        - name: TODO_API_URL
          value: http://todoapi
        volumeMounts: # 仮想Volumeによってnginxコンテナにも共有される
        - mountPath: /dist
          name: assets
